version: "3.8"

services:
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=popugafka
      - KRAFT_CREATE_TOPICS=users-stream,users-bussines-flow,tasks-stream,tasks-bussines-flow
      - KRAFT_PARTITIONS_PER_TOPIC=1
