source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'

gem 'turbo-rails'
gem 'webpacker', '~> 5.0'

gem 'bootsnap', '>= 1.4.4', require: false

gem 'devise'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'ulid-ruby'

gem 'karafka', git: 'git://github.com/karafka/karafka.git', branch: '2.0'
gem 'waterdrop', '2.0.4'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :development do
  gem 'web-console', '>= 4.1.0'

  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'

  gem 'spring'

  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
end
